# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.SmallIntegerField(choices=[(0, 'Operator'), (1, 'Client')], verbose_name='User type')),
                ('user_id', models.IntegerField(verbose_name='User Id')),
                ('action_type', models.SmallIntegerField(choices=[(0, 'Operator'), (1, 'Client')], verbose_name='Action type')),
                ('dump', models.TextField(blank=True, null=True, verbose_name='Dump')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='print_orders.PrintOrder', verbose_name='Order')),
            ],
        ),
    ]
